# This file configures the travis-ci.org builds

  # Project language
language: java

  # Defines what jdk:s the build will run in
jdk:
  - oraclejdk8

  #custom ant build instead of default "ant test"
script:
  - ant -f build-test.xml



  # uploads testresults and coverage to s3 bucket, access keys and s3 bucket
  # name is specified in travis repo settings
addons:
  artifacts:
    debug: true
    paths:
      - ./bin/test
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    bucket: inte-project
    s3_region: us-east-1 #eu-central-1 does not support v2 auth (can't use)
