package org.pucko.commands;

import org.pucko.core.InputHandler;
import org.pucko.core.OutputHandler;
import org.pucko.core.WorkingDirectory;

import java.util.ArrayList;

/**
 * Created by Tobias on 20/09/16.
 */
public class History extends Command {

    private boolean printHistory;

    /**
     * @param args             Arguments used during execution of command.
     * @param workingDirectory The working directory in which the command should execute.
     * @param outputHandler    Where the output generated by the command should be sent.
     * @param errorHandler     Where the errors generated by the should be sent.
     */
    public History(ArrayList<String> args, WorkingDirectory workingDirectory, OutputHandler outputHandler, OutputHandler errorHandler, InputHandler inputHandler) {
        super(args, workingDirectory, outputHandler, errorHandler, inputHandler);
    }

    @Override
    protected boolean execute() {
        int lastCommandToPrint;
        int commandIndex = 1;
        ArrayList<String> commandHistory = getInputHandler().getHistory();

        if (printHistory) {
            lastCommandToPrint = commandHistory.size();
        } else {
            lastCommandToPrint = Integer.parseInt(getArg(1));
        }

        for (int i = 0; i < lastCommandToPrint; i++) {
            output(commandIndex + "\t" + commandHistory.get(i));
            commandIndex++;
        }
        return true;

    }

    @Override
    protected boolean verifyExecutable() {

        int argsSize = getArgs().size();

        if (argsSize == 1) {
            printHistory = true;
            return true;
        }

        if (argsSize == 2) {

            int commandNumber;

            try {
                commandNumber = Integer.parseInt(getArg(1));
            } catch (NumberFormatException e) {
                error("Only numbers are accepted");
                return false;
            }

            if (commandNumber > getInputHandler().getHistory().size()) {
                error("Number greater than command history");
                return false;
            }

            if (commandNumber < 1) {
                error("Command number has to be > 0");
                return false;
            }
            return true;
        }

        error("Too many arguments");
        return false;
    }

    @Override
    protected boolean undo() {
        return false;
    }

    @Override
    protected boolean verifyUndoable() {
        return false;
    }


}
