package org.pucko.commands;

import java.util.ArrayList;

import org.pucko.core.OutputHandler;
import org.pucko.core.WorkingDirectory;

public class Pwd extends Command {


	/**
	 * @param args             Arguments used during execution of command.
	 * @param workingDirectory The working directory in which the command should execute.
	 * @param outputHandler    Where the output generated by the command should be sent.
	 * @param errorHandler     Where the errors generated by the should be sent.
	 */
	public Pwd(ArrayList<String> args, WorkingDirectory workingDirectory, OutputHandler outputHandler, OutputHandler errorHandler) {
		super(args, workingDirectory, outputHandler, errorHandler);
	}

	@Override
	public boolean execute() {
			output(getWorkingDirectory().toString());
			return true;
	}

	@Override
	protected boolean verifyExecutable() {
		if (getWorkingDirectory() == null) {
			return false;
		}
		return true;
	}

	@Override
	protected boolean undo() {
		return false;
	}


	@Override
	protected boolean verifyUndoable() {
		return false;
	}
}
